config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers:{
    registrations: "admins/registrations",
    sessions: "admins/sessions"
  }
  devise_for :drivers, controllers:{
    registrations: "drivers/registrations",
    sessions: "drivers/sessions"
  }
  devise_scope :drivers do
    post "driver/guest_sign_in", to: "drivers/sessions#new_guest"
  end
  devise_for :ad_clients, controllers:{
    registrations: "ad_clients/registration",
    sessions: "ad_clients/session"
  }
  devise_scope :ad_clients do
    post "ad_clients/guest_sign_in", to: "ad_clients/sessions#new_guest"
  end
  
  root :to => "homes#index"
  get "homes/index"
  get "homes/about" 
  
  resources :admins, only:[:index]
  
  namespace :admins do
    resources :ad_clients, only: [:index, :show, :update]
    resources :driver, only: [:index, :show, :update]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :contacts, only: [:index, :show]
  end
  
  resources :ad_clients, only:[:index, :show, :edit, :update] do 
      member do
        get :dashboard
        get :followings, :followers
      end
    scope module: :ad_clients do
      resources :complete_deals, only:[:index, :show, :create, :edit, :update]
      resources :ads
    end
  end 
  
  resources :drivers, only:[:index, :show, :edit, :update] do
      member do
        get :dashboard
        get :followings, :followers
        patch :is_active
      end
    resources :car_informations, only:[:index, :create, :edit, :update, :destroy]
    resources :transfer_informations, only:[:index, :create, :edit, :update, :destroy]
  end
  
  
  resources :contacts, only:[:new, :create, :index, :show, :update] do
    post :confirm, action: :confirm_new, on: :new
  end

  resources :ads, only:[:index, :show] do
    resources :chats, only: [:index, :create]
    resources :rooms, only: [:index, :show, :create]
    member do
      get :genre_search
      get :favorite_search
      get :apply
    end
    resources :favorites, only: [:create, :destroy]
  end
  
end

app/models/ad_client.rb
class AdClient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates_acceptance_of :terms, allow_nil: false, message: "※会員登録には利用規約への同意が必要です。", on: :create
  	validates :company_name, presence: true
  	validates :company_name_kana, presence: true,format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  	validates :ceo_name, presence: true
  	validates :ceo_name_kana, presence: true
  	validates :address, presence: true
  	validates :ceo_name_kana, presence: true
  	validates :telephone_number, presence: true
  	validates :email, presence: true
  	validates :registry_image, presence: {
  		message: -> (rec, data){
  			I18n.t('activemodel.errors.message.not_upload')
  		}
  	}
  
  	attachment :profile_image
  	attachment :registry_image
  
  	has_many :ads
  
  	has_many :rooms
  
  	has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  	has_many :followed, class_name: "RelationshipDriver", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  
  	has_many :following_driver, :through => :follower, :source => :followed #自分がフォローしているドライバー
  	has_many :follower_driver, :through => :followed, :source => :follower #自分をフォローしているドライバー
  
  	enum user_status: {not_check: 0, checked_indentification: 1}
  	# not_check: 未確認, checked_indentification: 本人確認済み
  
  	geocoded_by :address
  	after_validation :geocode
  
  	def follow(driver_id)
  		follower.create(followed_id: driver_id)
  	end
  	def unfollow(driver_id)
  		follower.find_by(followed_id: driver_id).destroy
  	end
  	def following(driver_id)
  		follower.find_by(followed_id: driver_id)
  	end
  
  	#ゲストユーザー
  	def self.guest_ad_client
  		AdClient.find_by!( email: 'client1@dmm.com')
  	end

end

app/controllers/ad_clients/confirmations_controller.rb
# frozen_string_literal: true

class AdClients::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/ad_clients/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class AdClients::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/ad_clients/passwords_controller.rb
# frozen_string_literal: true

class AdClients::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/ad_clients/registrations_controller.rb
# frozen_string_literal: true

class AdClients::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end
  def after_sign_in_path_for(resource)
    dashboard_ad_client_path(resource)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end
  def after_sign_out_path_for(resource)
    new_ad_client_session_path
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/ad_clients/sessions_controller.rb
# frozen_string_literal: true

class AdClients::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end
  
  # login as guest 
  def new_guest
    ad_client = AdClient.guest_ad_client
    sign_in ad_client
    redirect_to dashboard_ad_client_path(current_ad_client), notice: "ゲストユーザーとしてログインしました。"
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end
  
  def after_sign_in_path_for(resource)
    dashboard_ad_client_path(resource)
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  
  def after_sign_out_path_for(resource)
    new_ad_client_session_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/ad_clients/unlocks_controller.rb
# frozen_string_literal: true

class AdClients::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/ad_clients/_index.html.erb
<h3>広告主 一覧</h3>
	<% i = 0 %>
		<table class="table" id="none-border">
			<% ad_clients.each do |ad_client| %>
				<td>
					<%= link_to ad_client_path(ad_client.id),data: {"turbolinks" => false} do %>
					<%= attachment_image_tag ad_client,:profile_image, fallback: "no_image.jpg" ,class: "img_wrap", size:'200x160' %><br>
					<%= ad_client.company_name %><% end %><br>
					<%= ad_client.company_name_kana %><br>
				</td>
				<% i = i + 1 %>
				<% if i % 3 == 0 %>
				<tr></tr>
				<% end %>
			<% end %>
		</table>
	<div class="text-center"><%= paginate ad_clients, class: "paginate" %></div>
<% if ad_client_signed_in? %>
	<%= link_to dashboard_ad_client_path(current_ad_client) do %><i class="fas fa-angle-left"></i> マイページへ戻る<% end %>
<% elsif driver_signed_in?%>
	<%= link_to  dashboard_driver_path(current_driver) do %><i class="fas fa-angle-left"></i> トップページに戻る<% end %>
<% end %>

app/views/ad_clients/_profile.html.erb
<table class="table">
	<tr id="none-border">
		<td class="text-center image-circle">
			<%= attachment_image_tag ad_client, :profile_image, fallback: "no_image.jpg", class: "image-circle", size: "230x170"%>
		</td>
	</tr>
	<tr id="none-border">
		<td class="text-center">
			<%= ad_client.company_name %> さん
		</td>
	</tr>
</table>

app/views/ad_clients/_sidebar.html.erb
<div class="sidebar-area">
	<table class="table">
		<tr id="none-border">
			<td class="text-center image-circle" colspan="2">
				<%= attachment_image_tag ad_client, :profile_image, fallback: "no_image.jpg", class: "image-circle", size: "230x170"%>
			</td>
		</tr>
		<tr id="none-border">
			<td class="text-center" colspan="2">
				<%= ad_client.company_name %> さん
			</td>
		</tr>
		<tr id="none-border" follow_count_<%= ad_client.id %>>
			<%= render "relationship_drivers/follow_count_ad_client", ad_client: current_ad_client %>
		</tr>
	<% if current_ad_client == ad_client %>
		<tr id="none-border">
			<td class="text-center" colspan="2">
				<%= link_to new_ad_client_ad_path(current_ad_client), class: "btn01", data: {"turbolinks" => false } do %><span>新規広告依頼</span><% end %>
			</td>
		</tr>
	<% end %>
	</table>
	<table class="sidebar">
		<thead>
			<th class="side-menu-heading">メニュー</th>
		</thead>
		<tbody>
			<tr>
				<td><%= link_to "マイページ", dashboard_ad_client_path(current_ad_client), class:"side-menu" %></td>
			</tr>
			<tr>
				<td><%= link_to  "ドライバー 一覧", drivers_path, class:"side-menu" %></td>
			</tr>
			<tr>
				<td><%= link_to  "広告主一覧", ad_clients_path, class:"side-menu" %></td>
			</tr>
			<tr>
				<td><%= link_to "掲載広告一覧", ad_client_ads_path(current_ad_client), class:"side-menu" %></td>
			</tr>
			<tr>
				<td><%= link_to "広告一覧", ads_path(current_ad_client), class:"side-menu"  %></td>
			</tr>
			<tr>
				<td><%= link_to "取引一覧", dashboard_ad_client_path(current_ad_client), class:"side-menu" %></td>
			</tr>
			<tr>
				<td><%= link_to "お問い合わせ", new_contact_path, class:"side-menu" %></td>
			</tr>
		</tbody>
	</table><br>
	<table class="sidebar">
			<thead>
				<th class="side-menu-heading">設定</th>
			</thead>
		<tr>
			<td><%= link_to edit_ad_client_path(current_ad_client), class: "side-menu",data: {"turbolinks" => false} do %>アカウント<% end %></td>
		</tr>
		<tr>
			
		</tr>
		<tr>
			
		</tr>
		<tr>
			<td><%= link_to "ログアウト", destroy_ad_client_session_path, method: :delete, class:"side-menu" %></td>
		</tr>
	</table>
</div>

app/views/ad_clients/dashboard.html.erb
<div class="row">
	<div class="col-xs-3">
		<!-- サイドバー -->
		<%= render 'ad_clients/sidebar', ad_client: current_ad_client %>
	</div>
	<div class="col-xs-8">
		<%= render 'layouts/message_from_admin', ad_client: @ad_client %>
		<%= render 'rooms/index', rooms: @rooms %>
		<%= render 'under_deals/index_ad_client',under_deals: @under_deals, finish_deals: @finish_deals %>
	</div>
</div>

app/views/ad_clients/edit.html.erb
<div class="row">
	<div class = "col-xs-6 col-xs-offset-1">
		<%= form_for(@ad_client) do |f| %>
			<%= attachment_image_tag @ad_client, :profile_image,id: :prev_img, fallback: "no_image.jpg", size:'230x170'  %><br>
				<%= f.attachment_field :profile_image,  id: :update_img, class: "user_image" %><br>
				<table class="table .table-borderless">
					<tr>
						<th><%= f.label :会社名 %></th>
						<td><%= f.text_field :company_name, class: "form-control form-control-sm" %></td>
					</tr>
					<tr>
						<th><%= f.label :会社名（カナ） %></th>
						<td><%= f.text_field :company_name_kana, class: "form-control form-control-sm" %></td>
					</tr>
					<tr>
					<tr>
						<th><%= f.label :代表取締役名 %></th>
						<td><%= f.text_field :ceo_name, class: "form-control form-control-sm" %></td>
					</tr>
					<tr>
					<tr>
						<th><%= f.label :代表取締役名（カナ） %></th>
						<td><%= f.text_field :ceo_name_kana, class: "form-control form-control-sm" %></td>
					</tr>
					<tr>
						<th><%= f.label :郵便番号 %></th>
						<td><%= f.text_field :postal_code, class: "form-control form-control-sm" %></td>
					</tr>
					<tr>
						<th><%= f.label :住所 %></th>
						<td><%= f.text_field :address, class: "form-control form-control-sm" %></td>
					</tr>
					<tr>
						<th><%= f.label :電話番号 %></th>
						<td><%= f.text_field :telephone_number, class: "form-control form-control-sm" %></td>
					</tr>
					<tr>
						<th><%= f.label :メールアドレス %></th>
						<td><%= f.text_field :email, class: "form-control form-control-sm" %></td>
					</tr>
					<tr>
						<th></th>
						<td class="text-left"><%= button_tag :type => "submit", class: "btn03" do %><span>更新する</span><i class="fas fa-angle-double-right"></i><% end %></td></td>
					</tr>
				</table>
			<%= link_to dashboard_ad_client_path(current_ad_client) do %><i class="fas fa-angle-left"> マイページへ戻る</i><% end %>
		<% end %>
</div>

<!-- エラーメッセージ表示-->
<div class="row">
	<% if @ad_client.errors.any? %>
		<h3><%= @ad_client.errors.count %>error occurrence</h3><!--エラーメッセ-->
		<ul>
			<% @ad_client.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
</div>
<!-- エラーメッセージ表示-->

app/views/ad_clients/followers.html.erb
<div class="row">
	<div class="col-xs-3">
		<!-- サイドバー -->
		<% if ad_client_signed_in? %>
			<%= render 'ad_clients/sidebar', ad_client: current_ad_client %>
		<% elsif driver_signed_in?%>
			<%= render "drivers/sidebar", driver: current_driver %>
		<% end %>
	</div><br>
	<div class="col-xs-6">
		<h3>フォロワー リスト</h3>
			<table class="table">
				<thead>
					<tr>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @followers.each do |driver| %>
						<tr>
							<td><%= attachment_image_tag driver, :profile_image, fallback: "no-image-mini.jpg",size:'80x80' %></td>
							<td><%= driver.driver_name %></td>
							<td><%= link_to driver_path(driver), class: "btn02",data: {"turbolinks" => false} do %><span>詳細<i class="fas fa-arrow-right"></i><% end %></i></td>
						</tr>
					<%end %>
				</tbody>
		</table>
	</div>
</div>

app/views/ad_clients/followings.html.erb
<div class="row">
	<div class="col-xs-3">
		<!-- サイドバー -->
		<% if ad_client_signed_in? %>
			<%= render 'ad_clients/sidebar', ad_client: current_ad_client %>
		<% elsif driver_signed_in?%>
			<%= render "drivers/sidebar", driver: current_driver %>
		<% end %>
	</div><br>
	<div class="col-xs-6">
		<h3>フォロー リスト</h3>
			<table class="table">
				<thead>
					<tr>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @followings.each do |driver| %>
						<tr>
							<td><%= attachment_image_tag driver, :profile_image, fallback: "no-image-mini.jpg",size:'80x80' %></td>
							<td><%= driver.driver_name %></td>
							<td><%= link_to driver_path(driver), class: "btn02",data: {"turbolinks" => false} do %><span>詳細<i class="fas fa-arrow-right"></i><% end %></i></td>
						</tr>
					<%end %>
				</tbody>
		</table>
	</div>
</div>

app/views/ad_clients/index.html.erb
<div class="row">
	<div class="col-xs-3">
		<% if ad_client_signed_in? %>
				<%= render 'ad_clients/sidebar', ad_client: current_ad_client %>
		<% elsif driver_signed_in?%>
			<%= render "drivers/sidebar", driver: current_driver %>
		<% end %>
	</div>
	<div class="col-xs-8 col-xs-offset-1">
		<%= render 'ad_clients/index', ad_clients: @ad_clients %>
	</div>
</div>

app/views/ad_clients/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<% if ad_client_signed_in? %>
			<%= render 'ad_clients/sidebar' , ad_client: current_ad_client %>
		<% elsif driver_signed_in?%>
			<%= render "drivers/sidebar", driver: current_driver %>
		<% end %><br>
	</div>
	<div class="col-xs-9">
		<div class="row">
			<div class = "col-xs-6">
				<h4>広告主情報</h4>
					<%= attachment_image_tag @ad_client, :profile_image, fallback: "no_image.jpg", size:'230x170'  %><br>
						<div id="follow_ad_client_<%= @ad_client.id %>">
							<%= render "relationship_drivers/follow_ad_client", ad_client: @ad_client %>
						</div>
					<table class="table .table-borderless">
						<tr id="follow_count_<%= @ad_client.id %>">
							<%= render "relationship_drivers/follow_count_ad_client", ad_client: @ad_client %>
						</tr>
						<tr>
							<th>会社名</th>
							<td><%= @ad_client.company_name %></td>
						</tr>
						<tr>
							<th>会社名（カナ）</th>
							<td><%= @ad_client.company_name_kana %></td>
						</tr>
						<tr>
							<th>郵便番号</th>
							<td><%= @ad_client.postal_code %></td>
						</tr>
						<tr>
							<th>住所</th>
							<td><%= @ad_client.address %></td>
						</tr>
						<tr>
							<th>メールアドレス</th>
							<td><%= @ad_client.email %></td>
						</tr>
						<% if admin_signed_in? %>
						<tr>
							<th>ユーザーステータス</th>
							<td>
								<%= form_for @ad_client, url: ad_client_path(@ad_client), method: :patch do |f| %>
									<%= f.radio_button :is_active, :true, checed:true %>
									<%= f.label :有効 %>
									<%= f.radio_button :is_active, :false %>
									<%= f.label :無効 %>
									<%= f.submit "更新", class: "btn btn-primary",style: "margin-left:13px"%>
								<% end %>
							</td>
						</tr>
						<% end %>
					</table>
				<%= link_to ad_clients_path do %><i class="fas fa-angle-left"> 一覧ページへ戻る</i><% end %>
			</div>
			<div class="col-xs-6">
				<h4>所在地</h4>
					<div id ="map"></div>
						<script>
							var map;
							function initMap(){
								var lat_lng ={ lat: <%= @ad_client.latitude %>, lng: <%= @ad_client.longitude %>}

								map = new google.maps.Map(document.getElementById('map'), {
									center: lat_lng,
									zoom: 12,
								});
								marker = new google.map.Marker({
									position: lat_lng,
									map: map
								});
							}
						</script>
						<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap", async: true, defer: true)) ></script>
			</div>
		</div>
  </div>