config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers:{
    registrations: "admins/registrations",
    sessions: "admins/sessions"
  }
  devise_for :drivers, controllers:{
    registrations: "drivers/registrations",
    sessions: "drivers/sessions"
  }
  devise_scope :drivers do
    post "driver/guest_sign_in", to: "drivers/sessions#new_guest"
  end
  devise_for :ad_clients, controllers:{
    registrations: "ad_clients/registration",
    sessions: "ad_clients/session"
  }
  devise_scope :ad_clients do
    post "ad_clients/guest_sign_in", to: "ad_clients/sessions#new_guest"
  end
  
  root :to => "homes#index"
  get "homes/index"
  get "homes/about" 
  
  resources :admins, only:[:index]
  
  namespace :admins do
    resources :ad_clients, only: [:index, :show, :update]
    resources :driver, only: [:index, :show, :update]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :contacts, only: [:index, :show]
  end
  
  resources :ad_clients, only:[:index, :show, :edit, :update] do 
      member do
        get :dashboard
        get :followings, :followers
      end
    scope module: :ad_clients do
      resources :complete_deals, only:[:index, :show, :create, :edit, :update]
      resources :ads
    end
  end 
  
  resources :drivers, only:[:index, :show, :edit, :update] do
      member do
        get :dashboard
        get :followings, :followers
        patch :is_active
      end
    resources :car_informations, only:[:index, :create, :edit, :update, :destroy]
    resources :transfer_informations, only:[:index, :create, :edit, :update, :destroy]
  end
  
  
  resources :contacts, only:[:new, :create, :index, :show, :update] do
    post :confirm, action: :confirm_new, on: :new
  end

  resources :ads, only:[:index, :show] do
    resources :chats, only: [:index, :create]
    resources :rooms, only: [:index, :show, :create]
    member do
      get :genre_search
      get :favorite_search
      get :apply
    end
    resources :favorites, only: [:create, :destroy]
  end
  
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_admin!, except: [:new, :confirm_new, :create]
  
  def new
    @contact = Contact.new
  end
  
  def confirm_new
    @contact = Contact.new(contact_params)
    render :new unless @contact.valid?
  end
  
  def create
    @contact = Contact.new(contact_params)
    if params[:back].present?
      render :new
    elsif @contact.save
      redirect_to contacts_path
      flash[:notice] = "お問い合わせ内容が正常に送信されました。"
    else
      render :new
    end
  end  
  
  def update
    @contact = Contact.find(params[:id])
    @contact.update(contact_params)
    redirect_back(fallback_location: admins_path)
  end

  def show  
    @contact = Contact.find(params[:id])
  end

  def new_inquiry
    @contacts = Contact.where(work_status: "new_inquiry")
  end

  def working_inquiry
    @contacts = Contact.where(work_status: "working_inquiry")
  end

  def past_inquiry
    @contacts = Contact.where(work_status: "past_inqu")
  end



  private
  def contact_params
    params.require(:contact).permit(:name, :company_name, :telephone_number, :email, :content, :work_status)
  end
  
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_inquiry.html.erb
<div class="col-xs-9">
  <table class="table table-hover">
      <thead>
        <tr>
          <td>問い合わせ日</td>
          <td>名前</td>
          <td>会社名</td>
          <td>内容</td>
          <td colspan="2">詳細画面</td>
        </tr>
      </thead>
      <tbody>
       <% contacts.each do |c| %>
        <tr>
          <td><%= c.created_at.strftime("%Y-%m-%d") %></td>
          <td><%= c.name %></td>
          <td><%= c.company_name %></td>
          <td><%= c.content %></td>
          <td colspan="2">
            <%= link_to "詳細", contact_path(c.id), class: "btn-sm btn-success" %></td>
        </tr>
       <% end %>
      </tbody>
  </table>
    <% if contacts.blank? %>
      <div class="message-box">
        <h4>現在、該当の問い合わせはありません。</h4>
      </div>
    <% end %>
  <h5><%= link_to"▶︎ 前のページへ", admins_path %></h5>
</div>

app/views/contacts/confirm_new.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-1">
    <h3>確認画面</h3>
      <table class="table">
         <tr>
            <th>お名前</th>
            <td><%= @contact.name %></td>
          </tr>
          <tr>
            <th>会社名</th>
            <td><%= @contact.company_name %></td>
          </tr>
          <tr>
            <th>電話番号</th>
            <td><%= @contact.telephone_number %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= @contact.email  %></td>
          </tr>
          <tr>
            <th>お問い合わせ内容</th>
            <td><%= @contact.content %></td>
          </tr><br>
          <tr>
            <th></th>
            <td class="text-left">
            	<%= form_with model: @contact, local: true do |f| %>
            	  <%= f.hidden_field :name %>
            	  <%= f.hidden_field :company_name %>
            	  <%= f.hidden_field :telephone_number %>
            	  <%= f.hidden_field :email %>
            	  <%= f.hidden_field :content %>
              <%= f.submit "戻る", name: 'back', class: "btn04" %>
              <%= button_tag :type => "submit", class: "btn03" do %><span>送信する</span><i class="fas fa-angle-double-right"></i><% end %>
            </td>
          </tr>
        </table>
      <% end %>
  </div>
</div>

app/views/contacts/index.html.erb
<h3>
	お問い合わせをいただき誠にありがとうございます。<br>
	担当者より追ってご連絡させていたきます。<br>
</h3>

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-2">
    <h3>問い合わせフォーム</h3>
      <%= form_for @contact, url: confirm_new_contact_path do |f| %>
        <p>
          <%= f.label :お名前 %>
          <%= f.text_field :name, autofocus: true, autocomplete:"", placeholder:"お名前を入力", class: "form-control" %>
        </p>
        <p>
          <%= f.label :会社名 %>
          <%= f.text_field :company_name, autofocus: true, autocomplete:"", placeholder:"広告店の方は会社名の入力をお願いします", class: "form-control" %>
        </p>
        <p>
          <%= f.label :電話番号 %>
          <%= f.text_field :telephone_number, autofocus: true, autocomplete:"" , placeholder: "ハイフンは不要です",class: "form-control" %>
        </p>
        <p>
          <%= f.label :メールアドレス  %>
          <%= f.text_field :email, autofocus: true, placeholder: '半角英数字でご入力ください',class: "form-control"  %>
        </p>
        <p>
          <%= f.label :お問い合わせ内容 %>
          <%= f.text_area :content, autofocus: true, autocomplete:"", placeholder:"お問い合わせ内容をご入力ください", class: "form-control",:size => "60x10" %>
        </p>
        <p>
          <td class="text-center">
            <%= button_tag :type => "submit", class: "btn03" do %><span>確認画面へ進む</span><i class="fas fa-angle-double-right"></i><% end %>
        </p>
      <% end %><br>
        <% if ad_client_signed_in? %>
          <%= link_to dashboard_ad_client_path(current_ad_client) do %><i class="fas fa-angle-left"></i> マイページへ戻る<% end %>
        <% elsif driver_signed_in?%>
          <%= link_to  dashboard_driver_path(current_driver) do %><i class="fas fa-angle-left"></i> トップページに戻る<% end %>
        <% end %>
    </div>
    <div class="col-xs-3">
      <%= render 'layouts/error_messages', model: @contact %>
    </div>
  </div>
</div>

app/views/contacts/new_inquiry.html.erb
<h3>新規問い合わせ一覧</h3>
<%= render 'inquiry', contacts: @contacts %>

app/views/contacts/past_inquiry.html.erb
<h3>過去の問い合わせ一覧</h3>
<%= render 'inquiry', contacts: @contacts %>

app/views/contacts/show.html.erb
<div class="row">
  <div class="col-xs-6">
    <h3>問い合わせ詳細</h3>
      <table class="table table-hover ">
         <tr>
            <th class="active">名前</th>
            <td><%= @contact.name %></td>
          </tr>
        </th>
        <tr>
          <th class="active">会社名</th>
          <td><%= @contact.company_name %></td>
        </th>
        <tr>
          <th class="active">問い合わせ日</th>
          <td><%= @contact.created_at.strftime("%Y-%m-%d") %></td>
        </th>
        <tr>
          <th class="active">ステータス</th>
          <td>
            <%= form_for @contact, url: contact_path(@contact), method: :patch do |f| %>
              <%= f.select :work_status, Contact.work_statuses.keys.map{|k| [I18n.t("enums.contact.work_status.#{k}"),k]} %>
              <%= f.submit "更新" %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th class="active">内容</th>
          <td><%= @contact.content %></td>
        </tr>
      </table>
    </div>
    <div class="col-xs-6">
      <%= render 'layouts/error_messages', model: @contact %>
    </div>
  </div>
</div>

app/views/contacts/working_inquiry.html.erb
<h3>対応中の問い合わせ一覧</h3>
<%= render 'inquiry', contacts: @contacts %>