config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers:{
    registrations: "admins/registrations",
    sessions: "admins/sessions"
  }
  devise_for :drivers, controllers:{
    registrations: "drivers/registrations",
    sessions: "drivers/sessions"
  }
  devise_scope :drivers do
    post "driver/guest_sign_in", to: "drivers/sessions#new_guest"
  end
  devise_for :ad_clients, controllers:{
    registrations: "ad_clients/registration",
    sessions: "ad_clients/session"
  }
  devise_scope :ad_clients do
    post "ad_clients/guest_sign_in", to: "ad_clients/sessions#new_guest"
  end
  
  root :to => "homes#index"
  get "homes/index"
  get "homes/about" 
  
  resources :admins, only:[:index]
  
  namespace :admins do
    resources :ad_clients, only: [:index, :show, :update]
    resources :driver, only: [:index, :show, :update]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :contacts, only: [:index, :show]
  end
  
  resources :ad_clients, only:[:index, :show, :edit, :update] do 
      member do
        get :dashboard
        get :followings, :followers
      end
    scope module: :ad_clients do
      resources :complete_deals, only:[:index, :show, :create, :edit, :update]
      resources :ads
    end
  end 
  
  resources :drivers, only:[:index, :show, :edit, :update] do
      member do
        get :dashboard
        get :followings, :followers
        patch :is_active
      end
    resources :car_informations, only:[:index, :create, :edit, :update, :destroy]
    resources :transfer_informations, only:[:index, :create, :edit, :update, :destroy]
  end
  
  
  resources :contacts, only:[:new, :create, :index, :show, :update] do
    post :confirm, action: :confirm_new, on: :new
  end

  resources :ads, only:[:index, :show] do
    resources :chats, only: [:index, :create]
    resources :rooms, only: [:index, :show, :create]
    member do
      get :genre_search
      get :favorite_search
      get :apply
    end
    resources :favorites, only: [:create, :destroy]
  end
  
end

app/models/driver.rb
class Driver < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates_acceptance_of :terms, allow_nil: false, message: "※会員登録には利用規約への同意が必要です。", on: :create
    validates :driver_name, presence: true
  	validates :driver_name_kana, presence: true,format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  	validates :postal_code, presence: true
  	validates :address, presence: true
  	validates :telephone_number, presence: true
  	validates :email, presence: true
  	validates :activity_area, presence: true
  
  	validates :driver_license_image, presence: {
  		message: -> (rec, data){
  			I18n.t('activemodel.errors.message.not_upload')
  		}
  	}
  
  	attachment :profile_image
  	attachment :driver_license_image
  
  	has_many :transfer_informations
  	has_many :car_informations
  	has_many :favorites, dependent: :destroy
  
  	has_many :chats
  	has_many :rooms
  
  	has_many :under_deals
  
  	has_many :follower, class_name: "RelationshipDriver", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  	has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  
  	has_many :following_ad_client, :through => :follower, :source => :followed #自分がフォローしている広告主
  	has_many :follower_ad_client, :through => :followed, :source => :follower #自分をフォローしている広告主
  
  	enum user_status: {not_check: 0, checked_indentification: 1, checked_car_indentification: 2,}
  	# not_check: 未確認, checked_indentification: 本人確認済み, checked_car_indentification: 車両情報確認済み
  
  
  	geocoded_by :activity_area
  	after_validation :geocode
  
  	def follow(ad_client_id)
  		follower.create(followed_id: ad_client_id)
  	end
  	def unfollow(ad_client_id)
  		follower.find_by(followed_id: ad_client_id).destroy
  	end
  	def following(ad_client_id)
  		follower.find_by(followed_id: ad_client_id)
  	end
  
  	#　ゲストユーザーログイン
  	def self.guest
  		find_by!( email: 'driver1@dmm.com')
  	end
         
         
end

app/controllers/admins/drivers_controller.rb
class Admins::DriversController < ApplicationController
  def index
  end
  
  def show
  end
end

app/controllers/drivers/confirmations_controller.rb
# frozen_string_literal: true

class Drivers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/drivers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Drivers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/drivers/passwords_controller.rb
# frozen_string_literal: true

class Drivers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/drivers/registrations_controller.rb
# frozen_string_literal: true

class Drivers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end
  
  def after_sign_in_path_for(resource)
    dashboard_driver_path(resource)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end
  
  def after_sign_out_path_for(resource)
    new_driver_path
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/drivers/sessions_controller.rb
# frozen_string_literal: true

class Drivers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end
  
  # ゲストユーザーログイン
  def new_guest
    driver = Driver.guest
    sign_in driver
    redirect_to dashboard_driver_path(current_driver), notice: "ゲストユーザーとしてログインしました。"
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end
  
  def after_sign_in_path_for(resource)
    dashboard_driver_path(resource)
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  
  def after_sign_out_path_for(resource)
    new_driver_session_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/drivers/unlocks_controller.rb
# frozen_string_literal: true

class Drivers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :authenticate_driver!, only:[:dashboard, :edit, :update]
  
  # ドライバー用のダッシュボード画面
  def dashboard
    @driver = Driver.find(params[:id])
    @under_deals = UnderDeal.includes(:ad, :deal_messages).references(:ad, :deal_messages).where(driver_id: @driver.id)
    @under_deal = @under_deals.includes(:ad, :deal_messages).references(:ad, :deal_messages).where.not(work_status: "finished").where.not(work_status: "checked_refuse").first
    @finish_deals = @under_deals.where(work_status: "finished").or(@under_deals.where(work_status: "checked_refuse"))
    if @under_deal.present?
      @ad = @under_deal.ad
      @messages = @under_deal.deal_messages
      @message = DealMessage.new()
      @deal_detail = DealDetail.new(deal_detail_params)
    end
  end  
  
  # 非ログインユーザー/広告主から見るドライバー一覧画面
  def index
    @ad_client = current_ad_client
    @driver = current_driver
    @drivers = Driver.page(params[:page]).per(9)
  end

  # 非ログインユーザー/広告主から見るドライバー詳細画面
  def show
    @driver = Driver.find(params[:id])
    @genres = Genre.all
    @car_informations = @driver.car_informations
    @ad_client = current_ad_client
  end
  
  #ドライバー側の編集ページ表示
  def edit
    @driver = Driver.includes(:transfer_informations, :car_informations).find(params[:id])
  end
  
  #ドライバー側の編集アップロード
  def update
    @driver = Driver.find(params[:id])
    if @driver.update(driver_params)
      redirect_back(fallback_location: edit_driver_path)
    else
      render :edit
    end
  end

  # フォロー機能
  def followings
    @driver = Driver.find(params[:id])
    @followings = @driver.following_ad_client
  end
  
  def followers
    @driver = Driver.find(params[:id])
    @followers = @driver.follower_ad_client
  end
  
  private
  def driver_params
    params.require(:driver).permit(:driver_name, :driver_name_kana, :profile_image, :postal_code, :address, :telephone_number, :is_active, :activity_area)
  end
  
  def message_params
    params.require(:deal_message).permit(:message, :user_type, :under_deal_id)
  end
  
  def deal_detail_params
    params.permit(:transfer_status, :bank_name, :branch_name, :account_type, :account_number, :account_name)
  end
  
  
end

app/helpers/admins/drivers_helper.rb
module Admins::DriversHelper
end

app/views/drivers/_index.html.erb
<h3>ドライバー 一覧</h3>
	<% i = 0 %>
		<table class="table" id="none-border">
			<% drivers.each do |driver| %>
				<td>
					<%= link_to driver_path(driver.id),data: {"turbolinks" => false} do %>
					<%= attachment_image_tag driver,:profile_image, fallback: "no_image.jpg", size:'200x160',class: "img_wrap" %><br>
					<%= driver.driver_name %><% end %><br>
					<%= driver.driver_name_kana %><br>
				</td>
				<% i = i + 1 %>
				<% if i % 3 == 0 %>
					<tr></tr>
				<% end %>
			<% end %>
		</table>
	<div class="text-center"><%= paginate drivers, class: "paginate" %></div>
<% if ad_client_signed_in? %>
	<%= link_to "マイページへ戻る", dashboard_ad_client_path(current_ad_client) %>
<% elsif driver_signed_in?%>
	<%= link_to "トップページに戻る", dashboard_driver_path(current_driver) %>
<% end %>

app/views/drivers/_profile.html.erb
<table class="table">
    <tr id="none-border">
        <td class="text-center">
            <%= attachment_image_tag driver, :profile_image, fallback: "no_image.jpg", class: "image-circle", size: "230x170" %>
        </td>
    </tr>
    <tr id="none-border">
        <td class="text-center">
            <%= driver.driver_name %> さん
        </td>
    </tr>
    <% if current_driver == driver %>
    <tr id="none-border">
        <td class="text-center">
            <%= link_to edit_driver_path(current_driver), class: "btn01",data: {"turbolinks" => false} do %><span>ドライバー情報 編集</span><% end %>
        </td>
    </tr>
    <% end %>
</table>

app/views/drivers/_sidebar.html.erb
<div class="sidebar-area">
	<table class="table">
		<tr id="none-border">
			<td class="text-center" colspan="2">
				<%= attachment_image_tag driver, :profile_image, fallback: "no_image.jpg", class: "image-circle", size: "230x170" %>
			</td>
		</tr>
		<tr id="none-border">
			<td class="text-center" colspan="2">
				<%= driver.driver_name %> さん
			</td>
		</tr>
		<tr id="none-border" follow_count_<%= driver.id %>>
			<%= render "relationships/follow_count_driver", driver: current_driver %>
		</tr>
		<% if current_driver == driver %>
		<tr id="none-border">
			<td class="text-center " colspan="2">
				<%= link_to edit_driver_path(current_driver), class: "btn01",data: {"turbolinks" => false} do %><span>ドライバー情報 編集</span><% end %>
			</td>
		</tr>
		<% end %>
	</table>
	<table class="sidebar">
		<thead>
			<th class="side-menu-heading">メニュー</th>
		</thead>
		<tbody>
			<tr>
				<td><%= link_to "マイページ", dashboard_driver_path(current_driver), class:"side-menu" %></td>
			</tr>
			<tr>
				<td><%= link_to "お気に入り広告", favorite_search_ad_path(current_driver), class:"side-menu" %></td>
			</tr>
			<tr>
				<td><%= link_to  "広告を探す", ads_path, class:"side-menu" %></td>
			</tr>
			<tr>
				<td><%= link_to  "広告主一覧", ad_clients_path, class:"side-menu" %></td>
			</tr>
			<tr>
				<td><%= link_to "取引情報", dashboard_driver_path(current_driver), class:"side-menu" %></td>
			</tr>
			<tr>
				<td><%= link_to "お問い合せ", new_contact_path, class:"side-menu" %></td>
			</tr>
		</tbody>
	</table><br>
	<table class="sidebar">
			<thead>
				<th class="side-menu-heading">設定</th>
			</thead>
		<tr>
			<td><%= link_to edit_driver_path(current_driver), class: "side-menu",data: {"turbolinks" => false} do %>アカウント<% end %></td>
		</tr>
		<tr>
			<td><%= link_to "口座情報", driver_transfer_informations_path(current_driver) , class: "side-menu",data: {"turbolinks" => false} %>
		</tr>
		<tr>
			<td><%= link_to "車両情報", driver_car_informations_path(current_driver) , class: "side-menu",data: {"turbolinks" => false} %>
		</tr>
		<tr>
			<td><%= link_to "ログアウト", destroy_driver_session_path, method: :delete, class:"side-menu" %></td>
		</tr>
	</table>
</div>

app/views/drivers/edit.html.erb
<div class="row">
	<div class = "col-xs-5 col-xs-offset-1">
	<h4>プロフィール情報</h4>
	<%= form_for(@driver) do |f| %>
		<%= attachment_image_tag @driver, :profile_image, id: :prev_img, fallback: "no_image.jpg", size:'230x170'  %><br>
		<%= f.attachment_field :profile_image,id: :update_img %><br>
		<table class="table .table-borderless">
			<tr>
				<th><%= f.label :driver_name %></th>
				<td><%= f.text_field :driver_name, class: "form-control form-control-sm" %></td>
			</tr>
			<tr>
				<th><%= f.label :driver_name_kana %></th>
				<td><%= f.text_field :driver_name_kana, class: "form-control form-control-sm" %></td>
			</tr>
			<tr>
				<th><%= f.label :postal_code %></th>
				<td><%= f.text_field :postal_code, class: "form-control form-control-sm" %></td>
			</tr>
			<tr>
				<th><%= f.label :address %></th>
				<td><%= f.text_field :address, class: "form-control form-control-sm" %></td>
			</tr>
			<tr>
				<th><%= f.label :telephone_number %></th>
				<td><%= f.text_field :telephone_number, class: "form-control form-control-sm" %></td>
			</tr>
			<tr>
				<th><%= f.label :email %></th>
				<td><%= f.text_field :email, class: "form-control form-control-sm" %></td>
			</tr>
			<tr>
				<th><%= f.label :activity_area %></th>
				<td>(例)東京都港区<%= f.text_field :activity_area, placeholder:"都道府県と市町村名までを入力", class: "form-control"%></td>
			</tr>
			<tr>
				<th></th>
				<td class="text-left"><%= button_tag :type => "submit", class: "btn03" do %><span>更新する</span><i class="fas fa-angle-double-right"></i><% end %></td>
			</tr>
			<% end %>
		</table>
		<%= link_to dashboard_driver_path(current_driver) do %><i class="fas fa-angle-left"> マイページへ戻る</i><% end %>
	</div>
	<div class = "col-xs-5">
		<h4>広告活動地域</h4>
			<div id="map"></div>
			<script>
				var map;
					function initMap(){
						var lat_lng ={ lat: <%= @driver.latitude %>, lng: <%= @driver.longitude %>}

						map = new google.maps.Map(document.getElementById('map'), {
							center: lat_lng,
							zoom: 12,
						});
						marker = new google.map.Marker({
							position: lat_lng,
							map: map
						})
					}
				</script>
			<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap", async: true, defer: true)) ></script>
		<table class="table .table-borderless">
			<tr>
				<th>振込先情報</th>
					<% if  @driver.transfer_informations.present?  %>
						<td><%= link_to driver_transfer_informations_path(@driver.id), class: "btn03",data: {"turbolinks" => false} do %><span>編集する</span><i class="fas fa-angle-double-right"></i><% end %></td>
					<% else %>
						<td><%= link_to "登録する", driver_transfer_informations_path(@driver.id) , class: "btn btn-primary",data: {"turbolinks" => false} %><p class="alert">口座情報が登録されていません。</p></td>
					<% end %>
			</tr>
			<tr>
				<th>登録車情報</th>
					<% if @driver.car_informations.present?  %>
						<td><%= link_to driver_car_informations_path(@driver.id), class: "btn03",data: {"turbolinks" => false} do %><span>編集する</span><i class="fas fa-angle-double-right"></i><% end %></td>
					<% else %>
						<td><%= link_to "登録する", driver_car_informations_path(@driver.id) , class: "btn btn-primary",data: {"turbolinks" => false} %><p class="alert">車両情報が登録されていません。</p></td>
				<% end %>
			</tr>
		</table>
	</div>
</div>
<!-- エラーメッセージ表示-->
<div class="row">
	<% if @driver.errors.any? %>
		<h3><%= @driver.errors.count %>error occurrence</h3>
		<ul>
			<% @driver.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
</div>

app/views/drivers/followers.html.erb
<div class="row">
	<div class="col-xs-3">
		<!-- サイドバー -->
		<% if ad_client_signed_in? %>
			<%= render 'ad_clients/sidebar', ad_client: current_ad_client %>
		<% elsif driver_signed_in?%>
			<%= render "drivers/sidebar", driver: current_driver %>
		<% end %>
	</div><br>
	<div class="col-xs-6">
		<h3>フォロワー リスト</h3>
		<table class="table">
			<thead>
				<tr>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @followers.each do |ad_client| %>
					<tr>
						<td><%= attachment_image_tag ad_client, :profile_image, :fill, 80, 80, fallback: "no-image-mini.jpg" %></td>
						<td><%= ad_client.company_name %></td>
						<td><%= link_to ad_client, class: "btn02", data: {"turbolinks" => false} do %><span>詳細<i class="fas fa-arrow-right"></i><% end %></td>
					</tr>
			 <% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/drivers/followings.html.erb
<div class="row">
	<div class="col-xs-3">
		<!-- サイドバー -->
		<% if ad_client_signed_in? %>
			<%= render 'ad_clients/sidebar', ad_client: current_ad_client %>
		<% elsif driver_signed_in?%>
			<%= render "drivers/sidebar", driver: current_driver %>
		<% end %>
	</div><br>
	<div class="col-xs-6">
		<h3>フォロー リスト</h3>
			<table class="table">
				<thead>
					<tr>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @followings.each do |ad_client| %>
					<tr>
						<td><%= attachment_image_tag ad_client, :profile_image, :fill, 80, 80, fallback: "no-image-mini.jpg" %></td>
						<td><%= ad_client.company_name %></td>
						<td><%= link_to ad_client, class: "btn02", data: {"turbolinks" => false} do %><span>詳細<i class="fas fa-arrow-right"></i><% end %></td>
					</tr>
					<%end %>
				</tbody>
		</table>
	</div>
</div>

app/views/drivers/index.html.erb
<div class="row">
	<div class="col-xs-3">
		<% if ad_client_signed_in? %>
			<%= render 'ad_clients/sidebar' , ad_client: current_ad_client %>
		<% elsif driver_signed_in?%>
			<%= render "drivers/sidebar", driver: current_driver %>
		<% end %>
	</div>
	<div class="col-xs-8 col-xs-offset-1">
		<%= render 'drivers/index', drivers: @drivers %>
	</div>
</div>

app/views/drivers/show.html.erb
	<div class="row">
		<div class="col-xs-3">
			<% if ad_client_signed_in? %>
				<%= render 'ad_clients/sidebar' , ad_client: current_ad_client %>
			<% elsif driver_signed_in?%>
				<%= render "drivers/sidebar", driver: current_driver %>
			<% end %>
		</div>
		<div class="col-xs-8">
			<div class="row">
				<div class = "col-xs-6">
				<%= attachment_image_tag @driver, :profile_image, fallback: "no_image.jpg", size:'230x170'  %><br>
					<div id="follow_driver_<%= @driver.id %>">
						<%= render "relationships/follow_driver", driver: @driver %>
					</div>
						<table class="table .table-borderless">
							<tr id="follow_count_<%= @driver.id %>">
								<%= render "relationships/follow_count_driver", driver: @driver %>
							</tr>
							<tr>
								<th>名前</th>
								<td><%= @driver.driver_name %></td>
							</tr>
							<tr>
								<th>名前（カナ）</th>
								<td><%= @driver.driver_name_kana %></td>
							</tr>
							<tr>
								<th>広告活動地域</th>
								<td><%= @driver.activity_area %></td>
							</tr>
							<tr>
								<th>メールアドレス</th>
								<td><%= @driver.email %></td>
							</tr>
							<% if admin_signed_in? %>
							<tr>
								<th>ユーザーステータス</th>
								<td>
									<%= form_for @driver, url: driver_path(@driver), method: :patch do |f| %>
										<%= f.radio_button :is_active, :true, checed:true %>
										<%= f.label :有効 %>
										<%= f.radio_button :is_active, :false %>
										<%= f.label :無効 %>
										<%= f.submit "更新", class: "btn btn-primary",style: "margin-left:13px"%>
									<% end %></td>
							</tr>
							<% end %>
						</table>
				</div>
				<div class = "col-xs-6">
					<h4>広告活動地域</h4>
						<div id ="map"></div>
							<script>
								var map;
								function initMap(){
									var lat_lng ={ lat: <%= @driver.latitude %>, lng: <%= @driver.longitude %>}

									map = new google.maps.Map(document.getElementById('map'), {
										center: lat_lng,
										zoom: 12,
									});
									marker = new google.map.Marker({
										position: lat_lng,
										map: map
									});
								}
							</script>
							<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap", async: true, defer: true)) ></script>
				</div>
			</div>

		<div class="col-xs-12">
			<table class="table">
		     <h3>Car infomartion</h3>
		      <thead>
		        <tr>
		          <td>メーカー</td>
		          <td>車名</td>
		          <td>ナンバープレート</td>
		          <td>車台番号</td>
		        </tr>
		      </thead>
		      <tbody>
		       <% @car_informations.each do |c| %>
		        <tr>
		          <td><%= c.manufacturer_name %></td>
		          <td><%= c.car_name %></td>
		          <td><%= c.license_plate %></td>
		          <td><%= c.flame_number %></td>
		        </tr>
		       <% end %>
		      </tbody>
	      </table>
	  </div>
	</div>